/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as coreHttp from "@azure/core-http";
import { FulfillmentOperations, SubscriptionOperations } from "./operations";
import { SaaSAPIContext } from "./saaSAPIContext";
import { SaaSAPIOptionalParams } from "./models";

export class SaaSAPI extends SaaSAPIContext {
  /**
   * Initializes a new instance of the SaaSAPI class.
   * @param credentials Subscription credentials which uniquely identify client subscription.
   * @param options The parameter options
   */
  constructor(
    credentials: coreHttp.TokenCredential | coreHttp.ServiceClientCredentials,
    options?: SaaSAPIOptionalParams
  ) {
    super(credentials, options);
    this.fulfillmentOperations = new FulfillmentOperations(this);
    this.subscriptionOperations = new SubscriptionOperations(this);
  }

  fulfillmentOperations: FulfillmentOperations;
  subscriptionOperations: SubscriptionOperations;
}
