/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as coreHttp from "@azure/core-http";
import { MeteringOperations } from "./operations";
import { MeteringAPIContext } from "./meteringAPIContext";
import { MeteringAPIOptionalParams } from "./models";

export class MeteringAPI extends MeteringAPIContext {
  /**
   * Initializes a new instance of the MeteringAPI class.
   * @param credentials Subscription credentials which uniquely identify client subscription.
   * @param options The parameter options
   */
  constructor(
    credentials: coreHttp.TokenCredential | coreHttp.ServiceClientCredentials,
    options?: MeteringAPIOptionalParams
  ) {
    super(credentials, options);
    this.meteringOperations = new MeteringOperations(this);
  }

  meteringOperations: MeteringOperations;
}
